name: Starter Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: demo workflow job
        run: | 
        echo This is a updated demo start workflow 
        pr_body="${{ github.event.pull_request.body }}"
        echo "$pr_body"